channels:                    # Lists package sources to install from
- defaults                   # Default Anaconda Repository
- conda-forge

dependencies:
# Building
- cmake
- ninja

# C++ libraries
- eigen >= 3.4 # Matrix and vectors
- ceres-solver >= 2.0 # Minimization problems
